from __future__ import annotations

from deepdive.models import ResearchReport


def report_to_markdown(report: ResearchReport) -> str:
    """Render a ResearchReport as a self-contained Markdown document."""
    lines: list[str] = []
    lines.append(f"# {report.question}\n")
    if report.summary:
        lines.append(report.summary.strip() + "\n")

    for section in report.sections:
        lines.append(f"## {section.heading}\n")
        lines.append(section.body.strip() + "\n")

    if report.sources:
        lines.append("## Sources\n")
        for i, src in enumerate(report.sources, 1):
            title = src.title or "Untitled"
            lines.append(f"{i}. [{title}]({src.url})")
        lines.append("")

    lines.append(
        f"\n---\n*Generated by DeepDive at {report.generated_at.isoformat()}"
        f" — cost ${report.total_cost_usd:.4f} USD*"
    )
    return "\n".join(lines)
