from __future__ import annotations

from deepdive.models import Claim, ResearchReport


def report_to_markdown(report: ResearchReport, *, include_evidence: bool = True) -> str:
    """Render a ResearchReport as a self-contained Markdown document.

    When ``include_evidence`` is True (the default), an "Evidence" appendix
    lists every claim with its verbatim source excerpt — the citation-honesty
    contract is visible to the reader, not buried in a JSON trace.
    """
    lines: list[str] = []
    lines.append(f"# {report.question}\n")
    if report.summary:
        lines.append(report.summary.strip() + "\n")

    for section in report.sections:
        lines.append(f"## {section.heading}\n")
        lines.append(section.body.strip() + "\n")

    if report.sources:
        lines.append("## Sources\n")
        for i, src in enumerate(report.sources, 1):
            title = src.title or "Untitled"
            lines.append(f"{i}. [{title}]({src.url})")
        lines.append("")

    all_claims = [c for s in report.sections for c in s.claims]
    grounded = sum(1 for c in all_claims if c.grounded)
    total = len(all_claims)

    if include_evidence and total > 0:
        lines.append("## Evidence\n")
        lines.append(
            f"_{grounded}/{total} claims are span-grounded "
            "(verbatim excerpt verified against source)._\n"
        )
        for i, claim in enumerate(all_claims, 1):
            lines.append(f"**{i}.** {claim.text}")
            for cit in claim.citations:
                marker = "✓" if cit.grounded else "✗"
                title = cit.title or "Untitled"
                lines.append(f"   - [{marker}] [{title}]({cit.url})")
                if cit.excerpt:
                    excerpt = cit.excerpt.replace("\n", " ").strip()
                    if len(excerpt) > 240:
                        excerpt = excerpt[:237] + "…"
                    lines.append(f"     > {excerpt}")
            lines.append("")

    grounding_note = ""
    if total > 0:
        grounding_note = f" — {grounded}/{total} grounded"

    lines.append(
        f"\n---\n*Generated by DeepDive at {report.generated_at.isoformat()}"
        f" — cost ${report.total_cost_usd:.4f} USD"
        f"{grounding_note}*"
    )
    return "\n".join(lines)


def _claim_status(claim: Claim) -> str:
    """Compact status marker for a claim. Public so other exporters can reuse."""
    return "grounded" if claim.grounded else "ungrounded"
