"""LaTeX exporter — produces a self-contained .tex document with \\cite{}s.

A separate `to_bibtex()` produces the matching .bib. Citation keys are derived
from the source URL via a deterministic slug so the .tex and .bib stay aligned.
"""

from __future__ import annotations

import hashlib
import re
from urllib.parse import urlparse

from deepdive.models import Citation, ResearchReport

_LATEX_ESCAPE = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(s: str) -> str:
    """Escape LaTeX special characters. Backslash first so subsequent escapes don't double-up."""
    out = []
    for ch in s:
        out.append(_LATEX_ESCAPE.get(ch, ch))
    return "".join(out)


def cite_key(citation: Citation) -> str:
    """Stable BibTeX citation key derived from URL host + 6-char hash.

    Stable across runs given the same URL — important for trace replay producing
    byte-identical .tex/.bib pairs.
    """
    host = (urlparse(str(citation.url)).hostname or "src").lower()
    safe = re.sub(r"[^a-z0-9]+", "", host)
    digest = hashlib.sha256(str(citation.url).encode("utf-8")).hexdigest()[:6]
    return f"{safe}_{digest}"


def to_latex(report: ResearchReport) -> str:
    """Render ``report`` as a standalone LaTeX document."""
    lines: list[str] = []
    lines.append(r"\documentclass[11pt]{article}")
    lines.append(r"\usepackage[utf8]{inputenc}")
    lines.append(r"\usepackage{hyperref}")
    lines.append(r"\usepackage{geometry}")
    lines.append(r"\geometry{margin=1in}")
    lines.append(r"\title{" + latex_escape(report.question) + "}")
    lines.append(r"\author{Generated by DeepDive}")
    lines.append(r"\date{" + report.generated_at.strftime("%Y-%m-%d") + "}")
    lines.append(r"\begin{document}")
    lines.append(r"\maketitle")

    if report.summary:
        lines.append(r"\begin{abstract}")
        lines.append(latex_escape(report.summary.strip()))
        lines.append(r"\end{abstract}")

    # Map URL → citation key for inline \cite{}s.
    url_to_key: dict[str, str] = {}
    for src in report.sources:
        url_to_key[str(src.url)] = cite_key(src)

    for section in report.sections:
        lines.append(r"\section{" + latex_escape(section.heading) + "}")
        body = latex_escape(section.body.strip())
        # Re-inject \cite{} calls where the original markdown had [N] markers.
        # We have the section's claims; resolve their citation URLs to keys.
        for claim in section.claims:
            for cit in claim.citations:
                key = url_to_key.get(str(cit.url))
                if key is not None:
                    # Append a \cite at end of body (best-effort — full inline
                    # placement requires LLM-aware rewriting).
                    body = body.rstrip()
                    if not body.endswith(r"\cite{" + key + "}"):
                        body += r" \cite{" + key + "}"
        lines.append(body)
        lines.append("")

    if report.sources:
        lines.append(r"\bibliographystyle{plain}")
        # User runs `bibtex` against the sibling .bib file (stem matches .tex stem).
        lines.append(r"\bibliography{references}")

    lines.append(r"\end{document}")
    return "\n".join(lines) + "\n"
