"""Notion-flavored Markdown exporter.

Notion accepts pasted Markdown and converts it to its block model. Some
quirks vs. standard Markdown:
  - Notion treats blockquote (``>``) as callouts when they start with an emoji
  - Headings deeper than ## are demoted in many views; we cap at ##
  - Inline code with backticks works
  - Links work; URLs without [text](url) wrapping become bare-URL embeds

The actual Notion API push is deferred to v0.4; this exporter writes a paste-
ready document so users get value today.
"""

from __future__ import annotations

from deepdive.models import ResearchReport


def to_notion_markdown(report: ResearchReport) -> str:
    """Render ``report`` as Notion-paste-friendly Markdown."""
    lines: list[str] = []
    lines.append(f"# {report.question}")
    lines.append("")

    if report.summary:
        lines.append(f"> 📝 {report.summary.strip()}")
        lines.append("")

    for section in report.sections:
        lines.append(f"## {section.heading}")
        lines.append("")
        lines.append(section.body.strip())
        lines.append("")

    if report.sources:
        lines.append("## Sources")
        lines.append("")
        for i, src in enumerate(report.sources, 1):
            title = src.title or "Untitled"
            lines.append(f"{i}. [{title}]({src.url})")
        lines.append("")

    grounded_total = sum(1 for s in report.sections for c in s.claims if c.grounded)
    total_claims = sum(len(s.claims) for s in report.sections)
    if total_claims > 0:
        lines.append("---")
        lines.append(
            f"> 🔍 *Generated by DeepDive — {grounded_total}/{total_claims} claims span-grounded.*"
        )

    return "\n".join(lines) + "\n"
