"""Obsidian exporter — Markdown with YAML frontmatter and [[wikilinks]].

Drop the file into your Obsidian vault and it shows up as a fully-indexed note
with linked sources. Each cited URL becomes a wikilink to a sibling note (which
Obsidian creates on first click).
"""

from __future__ import annotations

import re
from urllib.parse import urlparse

from deepdive.models import ResearchReport


def _slug(s: str) -> str:
    """Make an Obsidian-safe wikilink target from a URL or title."""
    s = re.sub(r"[\\/:*?\"<>|]", "-", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s[:100]


def _link_target(citation_title: str, url: str) -> str:
    """Pick the wikilink anchor — prefer a clean title, fall back to host."""
    if citation_title and citation_title.strip() and citation_title != "Untitled":
        return _slug(citation_title)
    host = urlparse(url).hostname or "source"
    return _slug(host)


def to_obsidian(report: ResearchReport) -> str:
    """Render ``report`` as Obsidian-flavored Markdown."""
    lines: list[str] = []

    # YAML frontmatter — Obsidian indexes these.
    lines.append("---")
    lines.append(f"title: {report.question}")
    lines.append(f"created: {report.generated_at.strftime('%Y-%m-%d')}")
    lines.append("source: deepdive")
    lines.append(f"sources_count: {len(report.sources)}")
    grounded_total = sum(1 for s in report.sections for c in s.claims if c.grounded)
    total_claims = sum(len(s.claims) for s in report.sections)
    lines.append(f"grounded: {grounded_total}/{total_claims}")
    lines.append("tags: [research, deepdive]")
    lines.append("---")
    lines.append("")

    lines.append(f"# {report.question}")
    lines.append("")
    if report.summary:
        lines.append(report.summary.strip())
        lines.append("")

    for section in report.sections:
        lines.append(f"## {section.heading}")
        lines.append("")
        lines.append(section.body.strip())
        lines.append("")

    if report.sources:
        lines.append("## Sources")
        lines.append("")
        for i, src in enumerate(report.sources, 1):
            target = _link_target(src.title or "", str(src.url))
            lines.append(f"{i}. [[{target}]] — [{src.title or 'Untitled'}]({src.url})")
        lines.append("")

    lines.append("---")
    lines.append(
        f"*Generated by DeepDive at {report.generated_at.isoformat()} — "
        f"{grounded_total}/{total_claims} grounded*"
    )
    return "\n".join(lines) + "\n"
